# Generated by Django 4.1.5 on 2023-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquaintance', '0002_rename_establishments_establishment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_gender',
            field=models.CharField(max_length=1, verbose_name='ищу'),
        ),
    ]
